### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Dexwell** [manuroe/messagerie#1]
Hey,

Is this project just a personal project to test new technologies, or are you turning it into a full-fledged Matrix app for Apple platforms? If the latter is the case, perhaps we could discuss collaborating as I'm also very interested in building a beautiful, easy-to-use Matrix app with mainstream appeal. It would be a waste to duplicate effort :)

Let me know!

**Comment by nustiueudinastea** [comment]
Not in any way related to the project but I wanted to let both of you know that I would definitely pay for a decent native macOS and iOS app.
